export const BUSINESS_CATEGORIES: string[] = [
  "Food & Beverage",
  "Retail",
  "Clothing & Apparel",
  "Beauty & Personal Care",
  "Health & Wellness",
  "Education & Training",
  "Technology",
  "Tourism & Hospitality",
  "Agriculture",
  "Logistics",
  "Finance",
  "Real Estate",
  "Services",
  "Manufacturing",
  "Arts & Crafts",
  "Nonprofit",
  "Other",
];
